### ISSUE TITLE
question about train

### ISSUE THREAD

**Issue by zhuangss** [black0017/MedicalZooPytorch#21]
When I used the mrbrains18 dataset for training, the following error occurred
Traceback (most recent call last):
  File "./train_mrbrains_9_classes.py", line 81, in <module>
    main()
  File "./train_mrbrains_9_classes.py", line 26, in main
    path='/home/zwj/MedicalZooPytorch-master/datasets/mrbrains_2018/training')
  File "/home/zwj/MedicalZooPytorch-master/lib/medloaders/__init__.py", line 50, in generate_datasets
    split_id=0, samples=samples_train, load=args.loadData)
AttributeError: 'Namespace' object has no attribute 'loadData'

**Comment by Juny-Chen** [comment]
i also meet this problem

**Comment by Chi20** [comment]
this problem too
---hope someone could solve this.

**Comment by Chi20** [comment]
find a solution for this problem：

**Comment by Chi20** [comment]
find a solution, who meet with this problem can add arguments not mentioned as below：
![1](https://user-images.githubusercontent.com/55939465/185949719-84c7409e-2e60-457c-85d3-20de13944aa8.png)
referring to:https://theaisummer.com/medical-image-deep-learning/#implementation-details   _Putting it all together/code_ part.

**Comment by Chi20** [comment]
Then you will meet with this problem

**Comment by Chi20** [comment]
Then you will meet with this problem:
![2](https://user-images.githubusercontent.com/55939465/185950422-b29de569-60f9-43ae-befe-6d0de44cbd5a.png)

**Comment by Grairain** [comment]
> Then you will meet with this problem: ![2](https://user-images.githubusercontent.com/55939465/185950422-b29de569-60f9-43ae-befe-6d0de44cbd5a.png)

do you know how to solve this???

**Comment by yeshunlong** [comment]
> > Then you will meet with this problem: ![2](https://user-images.githubusercontent.com/55939465/185950422-b29de569-60f9-43ae-befe-6d0de44cbd5a.png)
> 
> do you know how to solve this???

You can set loadData to False and run the train_with_trainer_class.py, then the *-samples-*.txt will be generated
