### ISSUE TITLE
ValueError: low >= high

### ISSUE THREAD

**Issue by maddy023** [black0017/MedicalZooPytorch#4]
!python test_covid_ct.py --dataset_name covid_seg
```
2020-05-01 11:52:26.733364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
COVID SEGMENTATION DATASET
0
Mode: train Subvolume samples to generate:  10  Volumes:  0
Traceback (most recent call last):
  File "test_covid_ct.py", line 76, in <module>
    main()
  File "test_covid_ct.py", line 27, in main
    path='.././datasets')
  File "/content/MedicalZooPytorch/lib/medloaders/__init__.py", line 79, in generate_datasets
    fold=args.fold_id, samples=samples_train, save=True)
  File "/content/MedicalZooPytorch/lib/medloaders/Covid_Segmentation_dataset.py", line 70, in __init__
    self.create_sub_volumes()
  File "/content/MedicalZooPytorch/lib/medloaders/Covid_Segmentation_dataset.py", line 96, in create_sub_volumes
    random_index = np.random.randint(total)
  File "mtrand.pyx", line 743, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1260, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

**Comment by black0017** [comment]
since the script outputs 0 it probably means that the paths are not configured correctly.
